import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../Components/Home/Layout';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" type="favicon.png" />
      </Head>
      <Layout />
    </>
  );
};

export default Home;
